name: Triggers the workflow on push or pull request events

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
      - run: npm run api 
      - run: npm run generate_types
      - run: npm run build
